[package]
name = "parsek"
version = "0.1.0"
authors = ["boolnulldot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rayon = "1.3.1"
url = "2.1.1"
hyper = "0.13.7"
hyper-tls = "0.4.3"
serde = { version="1.0", features=["derive"]}
serde_json = "1.0.57"
kuchiki = "0.8.0"
